name: iOS Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and Test using iPhone simulator
    runs-on: macos-15

    env:
      scheme: "Hauk"
      project: "Hauk.xcodeproj"
      project_type: "project"
      platform: "iOS Simulator"
      device: "iPhone 16"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          xcodebuild build-for-testing -scheme "$scheme" -"$project_type" "$project" -destination "platform=$platform,name=$device"
      - name: Test
        run: |
          xcodebuild test-without-building -verbose -scheme "$scheme" -"$project_type" "$project" -destination "platform=$platform,name=$device"
